README.md, src/server/config.js, src/server/datasource/aggregate.js, src/server/datasource/organisms.js, src/server/datasource/rank.js, src/server/db/db.js, src/server/routes/index.js, test/aggregate-quality.js, test/aggregate-verification.js, test/datasource.js, test/ncbi.js, test/temp/aggregate.js
- Ranking now happens in a separate thread for performance.
- The default result size is now 100 to make up for current so-so elasticsearch sorting.
- Add `MAX_SEARCH_ES` and `MAX_SEARCH_WS` to control the max return size for elasticsearch and for the webservice.  We need a higher return size for elasticsearch to do our own sorting.  The webservice only needs to return a small size (e.g. 10) because a user isn't going to look farther than that anyway.  And we need to make sure, realistically, that the expected result is at least in the top 3.
- Add support in the `/search` webservice to filter by a datasource `namespace`.  This could remove the need for separate endpoints like `/uniprot`.  Removing those endpoints and updating the swagger docs is still TODO.
- Updating the other …
=> Enable ranking within the aggregate service

test/util/data/molecular-cell.json
RE #18 
The groundings that were extracted are all correct -- relevant entities, right organism, tumor proteins if the paper speaks about tumor... What is obvious to me though, is that a lot is not picked up. It's very correct, but very conservative (which is not bad, per-se).
Another point is that it picks up families but it doesn't ground them to anything. This is known, I suppose. I also wonder what would be a good database for these (I was just looking around myself for this but apart from sparse wikipedia pages, I couldn't find a reliable resource).
=> Check groundings

test/util/data/molecular-cell.json, test/util/data/pc-blacklist.json, test/util/data/top-ncbi-gene.json
This covers some of the failures with the updates in ad5b7b600ae2ebf091886ba3e4e399fe619d2d88 and f5b6a5f761d744561ebbc8c45c3debc423dca643.
Most of these cases are just enabling the `loose` flag on cases that are inherently ambiguous.  By default, `loose: true` sets it so the test case passes if the expected result is in the top-3.  You can set a custom `loose: N` integer if you want to loosen the strictness further to the top-N.  That should only be done in special cases, and most should remain `loose: true`.
Some of the fixes are just typos.
Note: This doesn't review all of the failures.  I only got through part of them to see in what ways the search could be improved.
I added yeast variants to one of the yeast-specific papers, and that seemed to sort it out for that one.  The same …
=> Partial test json review

test/util/data/molecular-cell.json
I guess the first batch that I got was lucky. In this case, I found some sound scientifically but "don't know exactly what to do" grounding-wise papers. E.g. papers in which tumors grown in dishes from human cell lines get injected in vivo into mice. In these cases, I picked human as first organism, and mouse as second. In the case that the paper reported using viruses in essays, I appended the taxonomy id of the viruses as last ids in the array.
=> Grounded orgs for remaining papers

test/util/data/molecular-cell.json
Article test for 
- [Boekhout et al. Mol. Cell, April 16, 2019, REC114 Partner ANKRD31 Controls Number, Timing, and Location of Meiotic DNA Breaks](https://www.cell.com/molecular-cell/fulltext/S1097-2765(19)30227-8).
- [Chino et al. Mol. Cell, June 6, 2019, Intrinsically Disordered Protein TEX264 Mediates ER-phagy](https://www.cell.com/molecular-cell/fulltext/S1097-2765(19)30257-6).
=> Appended entity tests for mol cell [online now]

test/util/data/molecular-cell.json
Erroneously grounded everything to homo sapiens rather than mus musculus.
=> Updates tests for molecular cell https://doi.org/10.1016/j.molcel.2018.04.024

test/util/data/molecular-cell.json
Appending tests for Lane et al. https://doi.org/10.1016/j.molcel.201905.019.
Notable failures:  'insulin' is chebi first rather than ncbi
=> Tests: Case Study for Lane et al (https://doi.org/10.1016/j.molcel.201905.019)

.travis.yml, package-lock.json, package.json, src/server/datasource/aggregate.js, src/server/datasource/cli.js, src/server/datasource/ncbi.js, src/server/datasource/organisms.js, src/server/db/db.js
This PR is intended as a short-term substitute for merging strains at index time.
**Summary**
There are two problems with strains: (1) When a user gets entity results for similar strains of E. coli, he doesn't really care which one is selected.  It's just noise.  (2) There's an ambiguity problem inherent in having the same protein duplicated for several strains.
(1) is a UX issue, while (2) is a data provider issue.  We care more about the UX issue, so we can focus on that.  Really, (2) should be the responsibility of the data provider itself.
Previous attempts to solve this issue addressed both (1) and (2) by cleaning up the data.  This PR solves only (1) by filtering out duplicates after ranking at search time.
**Details**
This means that you only ever get the best matching entity per …
=> Do strain cleanup at search time

src/server/datasource/ncbi.js, test/ncbi.js
This revises groundings from NCBI to have the default type 'ggp' (gene or gene product).  Apps such as Factoid can refine the type to things like 'protein' based on user input.
Ref : Rename `type:'protein'` #44
=> Update NCBI datasource to give `type: 'ggp'`

package-lock.json, package.json, src/server/config.js, src/server/datasource/eutils.js, src/server/datasource/ncbi.js, src/server/datasource/organisms.js, src/server/datasource/processing.js, src/server/routes/index.js
Introduces three key pieces:
1. Wrapper for NCBI EUTILS
- Basically copy-paste from Factoid
2. Index proteins for a given taxon in `datasource.js/ncbi`
- Add SARS-CoV-2 genes from file using existing code
- Introduce protein-level records for SARS-CoV-2 due due to multiple mature protein chains derived from genes
- The complement of proteins is sourced from NCBI EUTILS, given an organisms ID
3. Indexing `processing.js`
- Index the SARS-CoV-2 records all at once from 'source' i.e, not a file
Notes:
- Overall grounding tests did not deviate much at all (~9% error rate) from before (analyzed about a year ago?)
- For proteins, synonyms are generated based upon the title/label which have some particular formatting in NCBI
- There's probably no consensus on synonyms or naming given how new this …
=> SARS-Cov-2 Support

src/server/config.js, src/server/datasource/chebi.js, src/server/datasource/ncbi.js, src/server/datasource/uniprot.js
Add two attributes: 
1. `dbPrefix`
- This contains the namespace for the database
- Use it like `https://identifiers.org/<dbPrefix>:<id>`
2. `dbName`
- This is the name (e.g. UniProt Knowledgebase). Useful for link display and used in BioPAX Xrefs
Refs #75
=> Add attributes to identify the source database

Dockerfile, package.json, src/server/datasource/cli.js, src/server/datasource/download.js
New npm script 'boot' that ties the success of a data 'refresh' (clear; update) to server 'start'. Docker default command is 'npm run boot' instead of 'npm start'.
Compensatory changes:
- Factoid docker-compose will be simplified, merging the 'grounding' and 'indexer' services into one (https://github.com/PathwayCommons/factoid/pull/802)
- ci server need updates to use 'boot' (TODO)
Refs #76
=> Server dependent on successful data refresh

src/server/datasource/aggregate.js, src/server/db/db.js
- Search queries allow for specifying `namespace` as an array of allowed namespaces to search.  Previously, only a single namespace was allowed.
- Set the default to `namespace = ['ncbi', 'chebi']` so that other namespaces can be indexed but not included in searches by default (e.g. Uniprot).
Refs. :
- PC-2-factoid: Supplementing the Factoid database with curated interactions https://github.com/PathwayCommons/factoid/issues/836
- Provide an admin facility to add articles using biopax file from url https://github.com/PathwayCommons/factoid/pull/881
=> Include only NCBI and CHEBI in aggregate search results by default

package.json, src/server/datasource/chebi.js, src/server/datasource/uniprot.js, src/server/parser/xml-parser.js
- `update` npm script now includes uniprot
-  UniProt now includes dbXrefs, in particular from NCBI Gene (aka `GeneID`)
- XML parsing
- This was not properly ignoring the tags in `omitList`, in particular, skipping children etc so had to update this in order to even access the dbXrefs in UniProt. 
Refs #88 and #89
=> Index UniProt and its associated dbXrefs

src/server/datasource/aggregate.js, src/server/db/db.js, src/server/routes/index.js
Provides for a new endpoint `/map` that takes one or more identifiers from a database and returns one or more identifiers from a desired database, if they exist. 
Basically this thing looks through the uniprot dbXrefs for the co-occurence of databases the user wishes to map between.  Supported databases include (MIRIAM prefix): ncbigene, refseq, chembl.target, ensembl, genecards, hgnc, reactome, go, interpro, pfam, supfam, uniprot. 
- input
- `id`:  a string or array of strings that represents identifiers
- `dbfrom`: MIRIAM prefix of database corresponding to the `id`(s)
- `dbto`: desired database in which to identify ids
- output
- Array, one object for each element of `id` 
- `dbfrom`, `id` from input
- `dbXrefs` 
- `db`, `id`
Example use:
IN
```json
{
"id": [
"NP_001119584.1"
], …
```
=> db: 'map' between selected database identifiers 

src/server/datasource/eutils.js, src/server/datasource/ncbi.js, src/server/datasource/organisms.js, src/server/db/patches.js
- adds support for SARS-CoV in same manner as SARS-CoV-2 before it
- fixes an existing bug in ESUMARY opts, which otherwise skipped over first record 
Refs #101
=> Sars-CoV support

test/aggregate-quality.js, test/util/data/molecular-cell.json
- Needed to accommodate the testing namespaces
- Bizarre species made their way into the `organismOrdering` in test data
=> Fix bugs in testing data and test harness.

src/server/config.js
https://github.com/PathwayCommons/grounding-search/issues/103#issuecomment-776182560
=> Correct typo in the `ZENODO_BASE_URL` env variable.

.gitignore, README.md, src/server/config.js, src/server/datasource/esdump.js
- Restore the elasticsearch index by pulling from a publicly available, published versions of a Zenodo record containing the index files
- Dumping and pushing to  Zenodo is as before, requiring API token and deposition information 
Notes:
- the production Zenodo data should first be published and this PR tested against it.
Refs #113
=> Restore index data from published record

src/server/config.js, src/server/routes/index.js, src/server/swagger/index.js
- Add `SWAGGER_HOST` env var.  This needs to be set for Docker configs etc.  By default, it points to `localhost:3000` so that it works out of the box for people who just clone the repo and start the service.  @jvwong, we may need a corresponding update to the Docker compose configs for Biofactoid.
- Docs for `/search`, `/get`, and `/map`.  @jvwong, could you check that your `/map` route isn't missing anything here?
- Examples are included with the Swagger docs, so on the page the user can just click a button to run an example query.  They don't have to write a bunch of JSON just to test things out.
- The Swagger docs page automatically displays the version number specified in `package.json`, so new releases will always display properly without extra prep work.
- For `localhost:3000`, …
=> Up-to-date Swagger

docker-compose.yml, src/server/db/db.js
Remove the mapping types due to deprecation in elasticsearch v7.
Test results:
| branch |   passes  |   failures  | 
|--------|----------|--------- |
| master |  698  |   61  |
| mapping-types |  698  |   61  |
Refs #132
=> Drop mapping types

src/server/config.js, src/server/datasource/famplex.js
Complexes are assigned a type `named-complex` to distinguish them from `complex`. Primary reason for this distinction is that existing (factoid) type `complex` are identified at the component-level, and much of the codebase expects the existence of child nodes.
Refs: https://github.com/PathwayCommons/grounding-search/issues/130#issuecomment-1544182783
=> Famplex Part III: `namedComplex`

src/server/datasource/aggregate.js, test/util/data/molecular-cell.json
Remove `filterSearchString` on queries. 
This function accommodated a single failing test case that in fact was not correct (i.e. `U6 snRNA` should be `U6`).
=> Remove extraineous filter on search string.

src/server/datasource/aggregate.js, src/server/datasource/famplex.js
Simply explain the purpose of filtering 'duplicate' entries from a species' strains in search results.
=> Document the purpose of search helper function 'filterStrains'.

test/aggregate-quality.js
Compare the `namespace` and `id` (not anything else) between ground truth and top hit returned.
Missed in #155.
=> Grounding tests: Compare database and ID only

test/aggregate-quality.js, test/util/quality-reporter.js
Hidden bug: aggregate test module assumes there will always be search results returned. This enables the tests and runners to accept zero search hit results.
=> Permit empty search results in aggregate tests.

src/server/config.js
Config with ES parameters that provide more stringent search, possibility of returning empty results for poor matches.
Refs #161 
---
Reposting from #162 (Green bars represent current settings)
**Figure 1.** Search accuracy over different configurations (N=868). A test case fails when the expected ground is not the top search result returned from the grounding-search.
**Figure 2.** Search errors grouped into different classes based on rank. Runner up is second hit; OOD is 'out of dictionary' meaning a ground does not exist but a (non-empty) search hit is returned.
=> More stringent Elasticsearch configuration
