- src/server/config.js
This really got me question life a couple times in the last 15 min
> Fix env var for ELASTICSEARCH_HOST

- test/util/data/top-ncbi-gene.json
- test/util/search.js
Adding tests including (up to) 25 of the top-cited genes for each organism.
> Top 25 in ncbi genes2pubmed mapping. 

- Dockerfile
> Dockerfile update.

- wait-for-elasticsearch.sh
This is useful with regards to Docker automation documentation. 
Refs 
- https://github.com/PathwayCommons/factoid/issues/451
- https://github.com/PathwayCommons/factoid/pull/478
> 'Wait for elasticsearch' script 

- test/util/data/molecular-cell.json
Species is human first, although there is mention of mouse. Other miscellaneous corrections.
> Corrections to test for Mol cell http://dx.doi.org/10.1016/j.molcel.2016.11.034

- test/util/data/molecular-cell.json
Adding tests from Mol Cell [Online Now] set:
- Balsa et al. https://doi.org/10.1016/j.molcel.2019.03.031
- Li et al. https://doi.org/10.1016/j.molcel.2019.04.003
- Tu et al. https://doi.org/10.1016/j.molcel.2019.04.005
- Wang et al. https://doi.org/10.1016/j.molcel.2019.04.009
- Ritchie et al. https://doi.org/10.1016/j.molcel.2019.05.006
> Adding Mol Cell case study tests

- test/util/data/molecular-cell.json
Tests for Mol Cell https://doi.org/10.1016/j.molcel.2019.04.026 (Ord et al) dealing with  yeast cell cycle.
> Case study tests j.molcel.2019.04.026

- test/util/data/molecular-cell.json
Appending test for Mayank et al https://doi.org/10.1016/j.molcel.201905.020
> Molcular Cell test for Mayank et al

- test/util/data/molecular-cell.json
- test/util/data/pc-blacklist.json
A few duplicates between and within data sources.
> Dropping duplicates.

- package-lock.json
- package.json
- src/server/datasource/ncbi.js
- src/server/datasource/organisms.js
- src/server/datasource/strains/root.js
- src/server/db/db.js
- src/server/util/index.js
- src/server/util/promises.js
- test/aggregate-verification.js
- test/datasource.js
- test/ncbi.js
- test/util/chai.js
> Merge entities that are associated with strains

- package-lock.json
- package.json
- test/aggregate-quality.js
- test/util/quality-reporter.js
- Dropped 'loose' in the quality tests 
- Custom reporter tailored to quality test output 
- Spits out csv for get and search result
> Quality test modification and custom reporter 

- src/server/datasource/aggregate.js
- src/server/datasource/ncbi.js
- src/server/db/db.js
- test/aggregate-quality.js
- test/ncbi.js
- Implemented steps discussed in #50.
- Fixed bug for not updating organism id of descendent strain entry for
normalization when there is no available root.
- Fixed mix of types problem in organisms field of strains.
> Implementation of #50 and bug fixes related to strains

- src/server/datasource/ncbi.js
- test/ncbi.js
> Merge the roots that has the same orgID, name combination into a single entity

- src/server/datasource/ncbi.js
- test/ncbi.js
> Merge by single synonyms

- src/server/datasource/ncbi.js
Adding to NCBI output:
- dbXref array (db, id)
- typeOfGene: which provides very specific gene info 
Refs #63
> NCBI Gene: Additional fields

- src/server/datasource/chebi.js
> ChEBI: Skip empty entries and make sure there's an id

- src/server/datasource/chebi.js
Add the ChEBI summary field, with human-readable description of the chemical (when available).
Refs #70
> Add ChEBI summary field.

- src/server/datasource/uniprot.js
Gene names are optional protein attribute so don't add 'undefined'.
Refs #85
> Check for gene names before adding to synonym list.

- src/server/datasource/download.js
Throws if a downloaded file is 0 bytes.
Refs #76
> Check empty downloads

- package-lock.json
```
rm -rf node_modules
rm package-lock.json
npm i
```
> Update to a fresh lock file

- src/server/datasource/download.js
> Forgot to actually set a non-zero minimum download size

- src/server/db/db.js
Refs https://github.com/PathwayCommons/grounding-search/pull/99#issuecomment-727019920
> Support OMIM mapping

- src/server/config.js
> Point to the new data by default

- README.md
- src/server/config.js
- test/util/data/famplex.json
- test/util/data/molecular-cell.json
- test/util/data/top-ncbi-gene.json
Adding FamPlex tests and removing erroneous cases in other test files where family entities were mentioned. Also config variables for Famplex data on GitHub.
Refs: https://github.com/PathwayCommons/grounding-search/issues/130#issuecomment-1544182783
> FamPlex Part 1: Test cases and corrections

- src/server/datasource/famplex.js
Set type to `protein`.
Refs #139
> Default FamPlex type

- package-lock.json
- package.json
Major changes:
- grounding search support for FamPlex entities.
> Version 1.2.0

- test/util/data/molecular-cell.json
- test/util/data/org-hints.json
- test/util/search.js
Tests cases for orthologues that would otherwise fail, if not for an explicit organismOrdering. The gene mentions are drawn from articles that specifically mention the species (and available in PubTator3) so would be ideal cases to test automated species extraction + grounding.
- Species: rat, mouse, fly, arabadopsis, fruit fly, zebrafish
> Orthologue tests

- test/aggregate-quality.js
- test/util/data/molecular-cell.json
- test/util/quality-reporter.js
Minor updates to the test quality module:
- Write the output to file
- Add esScore for the expected and actual search hits, when they exist
- Remove duplicate test case
Updated test results:
|type  |passes|failures|Top  |Top2 |
|------|------|--------|-----|-----|
|search|733   |60      |92.4%|96.7%|
|get   |793   |0       |     |     |
> Quality reporter:  ES score + file output

- src/server/db/db.js
**Master branch**
|type  |passes|failures|Top  |Top2 |
|------|------|--------|-----|-----|
|search|733   |60      |92.4%|96.7%|
|get   |793   |0       |     |     |
**This branch**
|type  |passes|failures|Top  |Top2 |
|------|------|--------|-----|-----|
|search|734   |59      |92.6%|96.8%|
|get   |793   |0       |     |     |
Refs #154
> Filter on namespaces.

- src/server/config.js
Data refreshed with Zenodo Deposition ID:12966833
> Bump the Zenodo data dep ID
